name: Gpipe
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.5.0
  - torchvision=0.6.0
  - graphviz
  - python-graphviz
  - networkx
  - tqdm
  - scikit-learn
  - pip
  - cython
  - pip:
      - git+https://github.com/networkx/networkx-metis.git
      - transformers>2.9.1
