"""AutoGenerated with:
python /home/saareliad/workspace/FTPipe/autopipe/partition.py cep --n_partitions 4 --partitioning_batch_size 32 --analysis_batch_size 32 --n_iter 10 -c najeeb6 --save_memory_mode --bwd_to_fwd_ratio 1 --partitioning_method METIS --N 50 --K 11 --C 20000
"""
import torch
import torch.functional
import torch.nn.functional
from torch import Tensor
import torch.nn as nn
from itertools import chain
from typing import Optional, Tuple, Iterator, Iterable, OrderedDict, Dict
import collections

from typing import Type
from torch.nn.modules.container import ParameterList
from torch.nn.modules.linear import Linear
from torch.nn.modules.batchnorm import BatchNorm1d
# this is an auto generated file do not edit unless you know what you are doing


# partition adjacency
# model inputs {0, 1}
# partition 0 {'inputs': {'input0'}, 'outputs': {1}}
# partition 1 {'inputs': {0, 'input0'}, 'outputs': {2}}
# partition 2 {'inputs': {1}, 'outputs': {3}}
# partition 3 {'inputs': {2}, 'outputs': {4}}
# partition 4 {'inputs': {3}, 'outputs': {'output'}}
# model outputs {4}


def create_pipeline_configuration(DEBUG=False, batch_size=32):
    config = {
        'batch_dim': 0,
        'depth': 10000,
        'basic_blocks': (ParameterList,Linear,BatchNorm1d),
        'model_inputs': {
            'input0': {
                'shape': torch.Size([32, 1225]),
                'dtype': torch.float32,
                'is_batched': True,
                'used_by': [0, 1]}},
        'model_outputs': {
            'Net/Linear[output_layer]': {
                'shape': torch.Size([32, 1]),
                'dtype': torch.float32,
                'is_batched': True,
                'created_by': 4}},
        'stages': {
            0: {
                'stage_cls': Partition0,
                'inputs': {
                    'input0': {
                        'shape': torch.Size([32, 1225]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1}},
                'outputs': {
                    'Net/SplitLinear[input_layer]/torch.nn.functional::linear_11': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]}},
                'devices': ['cpu' if DEBUG else 'cuda:0'],
                'stage_depth': 4},
            1: {
                'stage_cls': Partition1,
                'inputs': {
                    'input0': {
                        'shape': torch.Size([32, 1225]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'Net/SplitLinear[input_layer]/torch.nn.functional::linear_11': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_0': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_1': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_2': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_3': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]}},
                'devices': ['cpu' if DEBUG else 'cuda:1'],
                'stage_depth': 3},
            2: {
                'stage_cls': Partition2,
                'inputs': {
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_0': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_1': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_2': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'Net/SplitLinear[input_layer]/prim::ListConstruct_13_3': {
                        'shape': torch.Size([32, 459]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1}},
                'outputs': {
                    'Net/torch.nn.functional::leaky_relu_19': {
                        'shape': torch.Size([32, 1836]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]}},
                'devices': ['cpu' if DEBUG else 'cuda:2'],
                'stage_depth': 2},
            3: {
                'stage_cls': Partition3,
                'inputs': {
                    'Net/torch.nn.functional::leaky_relu_19': {
                        'shape': torch.Size([32, 1836]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2}},
                'outputs': {
                    'Net/BatchNorm1d[bn2]': {
                        'shape': torch.Size([32, 20000]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]}},
                'devices': ['cpu' if DEBUG else 'cuda:3'],
                'stage_depth': 1},
            4: {
                'stage_cls': Partition4,
                'inputs': {
                    'Net/BatchNorm1d[bn2]': {
                        'shape': torch.Size([32, 20000]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3}},
                'outputs': {
                    'Net/Linear[output_layer]': {
                        'shape': torch.Size([32, 1]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [-1]}},
                'devices': ['cpu' if DEBUG else 'cuda:4'],
                'stage_depth': 0}}}
    
    
    # switching batch size
    batch_dim = config['batch_dim']
    for d in chain(config['model_inputs'].values(),config['model_outputs'].values()):
        if d['is_batched']:
            shape = d['shape']
            d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    for s in config['stages'].values():
        for d in chain(s['inputs'].values(),s['outputs'].values()):
            if d['is_batched']:
                shape = d['shape']
                d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    return config

class Partition0(nn.Module):
    LAYER_SCOPES = [
        ]
    TENSORS = [
            'Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[2]',
            'Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[2]',
        ]
    def __init__(self, layers, tensors, device='cuda:0'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1]
        self.lookup = {'p_0': 'input_layer.weights.2',
                        'p_1': 'input_layer.biases.2'}
        self.to(self.device)

    def forward(self, *args):
        # Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[2] <=> self.p_0
        # Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[2] <=> self.p_1
        # input0 <=> x0
        x0 = unflatten(args,self.input_structure)[0]
        t_0 = torch.nn.functional.linear(x0, self.p_0, bias=self.p_1)
        # Returning:
        # Net/SplitLinear[input_layer]/torch.nn.functional::linear_11
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self, state)

    def named_parameters(self, recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, recurse=recurse)

    def named_buffers(self, recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition1(nn.Module):
    LAYER_SCOPES = [
        ]
    TENSORS = [
            'Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[0]',
            'Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[1]',
            'Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[3]',
            'Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[0]',
            'Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[1]',
            'Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[3]',
        ]
    def __init__(self, layers, tensors, device='cuda:1'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1]
        self.lookup = {'p_0': 'input_layer.weights.0',
                        'p_1': 'input_layer.weights.1',
                        'p_2': 'input_layer.weights.3',
                        'p_3': 'input_layer.biases.0',
                        'p_4': 'input_layer.biases.1',
                        'p_5': 'input_layer.biases.3'}
        self.to(self.device)

    def forward(self, *args):
        # Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[0] <=> self.p_0
        # Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[1] <=> self.p_1
        # Net/SplitLinear[input_layer]/ParameterList[weights]/Parameter[3] <=> self.p_2
        # Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[0] <=> self.p_3
        # Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[1] <=> self.p_4
        # Net/SplitLinear[input_layer]/ParameterList[biases]/Parameter[3] <=> self.p_5
        # input0 <=> x0
        # Net/SplitLinear[input_layer]/torch.nn.functional::linear_11 <=> x1
        x0, x1 = unflatten(args,self.input_structure)
        t_0 = torch.nn.functional.linear(x0, self.p_0, bias=self.p_3)
        t_1 = torch.nn.functional.linear(x0, self.p_1, bias=self.p_4)
        t_2 = torch.nn.functional.linear(x0, self.p_2, bias=self.p_5)
        t_2 = [t_0, t_1, x1, t_2]
        # Returning:
        # Net/SplitLinear[input_layer]/prim::ListConstruct_13
        return list(flatten(t_2))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self, state)

    def named_parameters(self, recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, recurse=recurse)

    def named_buffers(self, recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition2(nn.Module):
    LAYER_SCOPES = [
            'Net/BatchNorm1d[bn1]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:2'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [[1, 1, 1, 1]]
        self.lookup = {'l_0': 'bn1'}
        self.to(self.device)

    def forward(self, *args):
        # Net/BatchNorm1d[bn1] <=> self.l_0
        # Net/SplitLinear[input_layer]/prim::ListConstruct_13 <=> x0
        x0 = unflatten(args,self.input_structure)[0]
        t_0 = torch.cat(x0, dim=-1)
        t_0 = self.l_0(t_0)
        t_0 = torch.nn.functional.leaky_relu(t_0, negative_slope=0.01, inplace=False)
        # Returning:
        # Net/torch.nn.functional::leaky_relu_19
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self, state)

    def named_parameters(self, recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, recurse=recurse)

    def named_buffers(self, recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition3(nn.Module):
    LAYER_SCOPES = [
            'Net/Linear[h1_layer]',
            'Net/BatchNorm1d[bn2]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:3'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1]
        self.lookup = {'l_0': 'h1_layer',
                        'l_1': 'bn2'}
        self.to(self.device)

    def forward(self, *args):
        # Net/Linear[h1_layer] <=> self.l_0
        # Net/BatchNorm1d[bn2] <=> self.l_1
        # Net/torch.nn.functional::leaky_relu_19 <=> x0
        x0 = unflatten(args,self.input_structure)[0]
        t_0 = self.l_0(x0)
        t_0 = self.l_1(t_0)
        # Returning:
        # Net/BatchNorm1d[bn2]
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self, state)

    def named_parameters(self, recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, recurse=recurse)

    def named_buffers(self, recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition4(nn.Module):
    LAYER_SCOPES = [
            'Net/Linear[h2_layer]',
            'Net/BatchNorm1d[bn3]',
            'Net/Linear[output_layer]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:4'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1]
        self.lookup = {'l_0': 'h2_layer',
                        'l_1': 'bn3',
                        'l_2': 'output_layer'}
        self.to(self.device)

    def forward(self, *args):
        # Net/Linear[h2_layer] <=> self.l_0
        # Net/BatchNorm1d[bn3] <=> self.l_1
        # Net/Linear[output_layer] <=> self.l_2
        # Net/BatchNorm1d[bn2] <=> x0
        x0 = unflatten(args,self.input_structure)[0]
        t_0 = torch.nn.functional.leaky_relu(x0, negative_slope=0.01, inplace=False)
        t_0 = self.l_0(t_0)
        t_0 = self.l_1(t_0)
        t_0 = torch.nn.functional.leaky_relu(t_0, negative_slope=0.01, inplace=False)
        t_0 = self.l_2(t_0)
        # Returning:
        # Net/Linear[output_layer]
        return (t_0,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self, state)

    def named_parameters(self, recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, recurse=recurse)

    def named_buffers(self, recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


def traverse_model(module: nn.Module, depth: int, prefix: Optional[str] = None,
                   basic_blocks: Tuple[Type[nn.Module]] = (), full: bool = False) -> Iterator[
    Tuple[nn.Module, str, nn.Module, Optional[bool]]]:
    """
    iterate over model layers yielding the layer,layer_scope,encasing_module
    Parameters:
    -----------
    model:
        the model to iterate over
    depth:
        how far down in the model tree to go
    basic_blocks:
        a list of modules that if encountered will not be broken down
    full:
        whether to yield only layers specified by the depth and basic_block options or to yield all layers
    """
    if prefix is None:
        prefix = type(module).__name__

    for name, sub_module in module.named_children():
        scope = prefix + "/" + type(sub_module).__name__ + f"[{name}]"
        if len(list(sub_module.children())) == 0 or isinstance(sub_module, tuple(basic_blocks)) or depth == 0:
            if full:
                yield sub_module, scope, module, True
            else:
                yield sub_module, scope, module
        else:
            if full:
                yield sub_module, scope, module, False
            yield from traverse_model(sub_module, depth - 1, scope, basic_blocks, full)


def layerDict(model: nn.Module, depth=1000, basic_blocks=()) -> Dict[str, nn.Module]:
    return {s: l for l, s, _ in traverse_model(model, depth, basic_blocks=basic_blocks)}


def traverse_params_buffs(module: nn.Module, prefix: Optional[str] = None) -> Iterator[Tuple[torch.tensor, str]]:
    """
    iterate over model's buffers and parameters yielding obj,obj_scope

    Parameters:
    -----------
    model:
        the model to iterate over
    """
    if prefix is None:
        prefix = type(module).__name__

    # params
    for param_name, param in module.named_parameters(recurse=False):
        param_scope = f"{prefix}/{type(param).__name__}[{param_name}]"
        yield param, param_scope

    # buffs
    for buffer_name, buffer in module.named_buffers(recurse=False):
        buffer_scope = f"{prefix}/{type(buffer).__name__}[{buffer_name}]"
        yield buffer, buffer_scope

    # recurse
    for name, sub_module in module.named_children():
        yield from traverse_params_buffs(sub_module, prefix + "/" + type(sub_module).__name__ + f"[{name}]")


def tensorDict(model: nn.Module) -> OrderedDict[str, Tensor]:
    return collections.OrderedDict((s, t) for t, s in traverse_params_buffs(model))


def move_tensors(ts, device):
    def move(t):
        if isinstance(t, (nn.Module, Tensor)):
            return t.to(device)
        return t

    return nested_map(move, ts)


def nested_map(func, ts, full=False):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        return func(ts)
    elif isinstance(ts, (list, tuple, set)):
        return type(ts)(nested_map(func, t, full=full) for t in ts)
    elif isinstance(ts, dict):
        return {k: nested_map(func, v, full=full) for k, v in ts.items()}
    elif isinstance(ts, slice) and full:
        start = nested_map(func, ts.start, full=full)
        stop = nested_map(func, ts.stop, full=full)
        step = nested_map(func, ts.step, full=full)
        return slice(start, stop, step)
    return func(ts)


def flatten(ts):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        yield ts
    elif isinstance(ts, (list, tuple, set)):
        yield from chain(*[flatten(t) for t in ts])
    elif isinstance(ts, dict):
        yield from chain(*[flatten(t) for k, t in sorted(ts.items(), key=lambda t: t[0])])
    else:
        yield ts


def unflatten(xs, structure):
    return _unflatten(xs, structure)[0]


def _unflatten(xs, structure):
    if isinstance(structure, torch.Size):
        # torch.Size is subclass of tuple which is stupid
        return xs[0], 1

    if not isinstance(structure, (list, tuple, set, dict)):
        return xs[0], 1

    if isinstance(structure, (list, tuple, set)):
        offset = 0
        elements = []
        for s in structure:
            e, n = _unflatten(xs[offset:], s)
            elements.append(e)
            offset += n

        return type(structure)(elements), offset

    assert isinstance(structure, dict)
    offset = 0
    elements = dict()
    for k, v in sorted(structure.items(), key=lambda t: t[0]):
        e, n = _unflatten(xs[offset:], v)
        elements[k] = e
        offset += n

    return elements, offset


def state_dict(partition, *args, **kwargs):
    # we return the state dict of this part as it should be in the original model
    state = nn.Module.state_dict(partition, *args, **kwargs)
    lookup = partition.lookup
    result = dict()
    for k, v in state.items():
        if k in lookup:
            result[lookup[k]] = v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            result[new_k] = v
    return result


def load_state_dict(partition, state):
    reverse_lookup = {v: k for k, v in partition.lookup.items()}
    device = partition.device
    keys = list(partition.state_dict(None).keys())
    new_state = dict()
    for k in keys:
        if k in reverse_lookup:
            new_state[reverse_lookup[k]] = state[k].to(device)
            continue
        idx = k.rfind(".")
        to_replace = k[:idx]
        if to_replace in reverse_lookup:
            key = reverse_lookup[to_replace] + k[idx:]
            new_state[key] = state[k].to(device)
    nn.Module.load_state_dict(partition, new_state, strict=True)


def named_buffers(partition, recurse=True):
    # we return the named buffers of this part as it should be in the original model
    params = nn.Module.named_buffers(partition, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def named_parameters(partition, recurse=True):
    # we return the named parameters of this part as it should be in the original model
    params = nn.Module.named_parameters(partition, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def cpu(partition):
    partition.device = torch.device('cpu')
    return nn.Module.cpu(partition)


def cuda(partition, device=None):
    if device is None:
        device = torch.cuda.current_device()
    partition.device = torch.device(device)
    return nn.Module.cuda(partition, partition.device)


def to(partition, *args, **kwargs):
    device = None
    if 'device' in kwargs:
        device = kwargs['device']
    elif 'tensor' in kwargs:
        device = kwargs['tensor'].device
    if args:
        if isinstance(args[0], (torch.device, int, str)):
            device = args[0]
        if torch.is_tensor(args[0]):
            device = args[0].device
    if not (device is None):
        partition.device = torch.device(device)
    return nn.Module.to(partition, *args, **kwargs)

model_args = {'N': 50, 'C': 20000}
"""analysis summary
-I- Printing Report
Number of stages: 4
n_partitions:5, num_dummy_stages:1
unique_stages_on_same_gpu: [{1}, {0, 2}, {3}, {4}]
"stage_to_device_map": [0, 1, 0, 2, 3],
backward times include recomputation

Stage parameter count:
 {0: 562734, 1: 1688202, 2: 3672, 3: 36780000, 4: 20004001, 'total': 59038609}

GPU parameter count:
 {0: 566406, 1: 1688202, 3: 36780000, 4: 20004001, 'total': 59038609}

real times are based on real measurements of execution time (with communication) of generated partitions ms
forward {0: 0.33, 1: 0.18, 3: 0.79, 4: 0.47}
backward {0: 1.21, 1: 1.14, 3: 1.4, 4: 1.49}

Assuming bandwidth of 12 GBps between GPUs

communication volumes size of activations of each partition
0: input size:'0.39 MB', recieve_time:'0.03 ms', out:'0.29 MB', send time:'0.02 ms'
1: input size:'0.22 MB', recieve_time:'0.02 ms', out:'0.24 MB', send time:'0.02 ms'
3: input size:'0.24 MB', recieve_time:'0.02 ms', out:'2.56 MB', send time:'0.21 ms'
4: input size:'2.56 MB', recieve_time:'0.21 ms', out:'0.00 MB', send time:'0.00 ms'

Compuatation Communication ratio (comp/(comp+comm)):
forward {0: 0.93, 1: 0.89, 3: 0.73, 4: 1.0} 
backward {0: 0.97, 1: 0.98, 3: 0.99, 4: 0.86}

Analysis for T = fwd + bwd:
 {'expected_compute_utilization': {0: 0.76, 1: 0.65, 3: 1.0, 4: 0.9},
 'pipeline_no_comm': {0: 1.5, 1: 1.28, 3: 1.96, 4: 1.75, 'worstcase': 1.96},
 'pipeline_vs_seq_no_comm': 3.28,
 'pipeline_with_non_parallel_comm': {0: 1.54,
                                     1: 1.31,
                                     3: 2.19,
                                     4: 1.97,
                                     'worstcase': 2.19},
 'seq_no_comm_no_recomp': {0: 0.56, 1: 1.41, 2: 0.95, 3: 1.84, 4: 1.66}}

Analysis for T = (1-R)fwd + R*bwd:

Pipeline Slowdown: (compared to sequential executation with no communication, and same recompute policy)
forward 2.090
backward 1.200

Expected utilization by partition
forward {0: 0.39, 1: 0.2, 3: 0.73, 4: 0.6}
backward {0: 0.79, 1: 0.75, 3: 0.93, 4: 0.86}

worstcase: bwd: 1.493 fwd: 0.787
expected_speedup_compared_to_seq_no_recomp_no_comm: 2.819
Expected speedup for 4 partitions is: 2.653
Analysis max cuda memory used 0.30GB
"""