"""AutoGenerated with:
python -m autopipe.partition new_t5 --model_name_or_path t5-3b --t5_task squad1 --lmhead --n_iter 10 --analysis_batch_size 64 --partitioning_batch_size 64 --ct new_trace_cache_t53b_64_4_lg --cp new_prof_cache_t53b_64_4_lg --stateless_tied --lmhead --n_partitions 8 --max_seq_length 64 --answer_max_seq_length 4 --partitioning_method pipedream --preset pipedream --disable_op_profiling --dont_use_async_meta_alg --save_memory_mode --special_blocks T5Block --basic_blocks T5Block --output_file layer_graph_
"""
import torch
import torch.nn.functional
import math
import torch.functional
from torch import Tensor
import torch.nn as nn
from itertools import chain
from typing import Optional, Tuple, Iterator, Iterable, OrderedDict, Dict
import collections

from typing import Type
from models.new_t5_example.modeling_t5 import T5LayerNorm
from models.normal.NLP_models.stateless import StatelessEmbedding
from torch.nn.modules.linear import Linear
from torch.nn.modules.dropout import Dropout
from models.new_t5_example.modeling_t5 import T5Block
# this is an auto generated file do not edit unless you know what you are doing


# partition adjacency
# model inputs {0, 5, 7}
# partition 0 {'inputs': {'decoder_input_ids', 'input_ids', 'attention_mask'}, 'outputs': {1, 2, 3, 4, 5}}
# partition 1 {'inputs': {0}, 'outputs': {2}}
# partition 2 {'inputs': {0, 1}, 'outputs': {3}}
# partition 3 {'inputs': {0, 2}, 'outputs': {4}}
# partition 4 {'inputs': {0, 3}, 'outputs': {5}}
# partition 5 {'inputs': {0, 4, 'attention_mask', 'decoder_attention_mask', 'decoder_input_ids'}, 'outputs': {6, 7}}
# partition 6 {'inputs': {5}, 'outputs': {7}}
# partition 7 {'inputs': {'labels', 5, 6}, 'outputs': {'output'}}
# model outputs {7}


def create_pipeline_configuration(DEBUG=False, batch_size=64):
    config = {
        'batch_dim': 0,
        'depth': 10000,
        'basic_blocks': (T5LayerNorm,StatelessEmbedding,Linear,Dropout,T5Block),
        'model_inputs': {
            'attention_mask': {
                'shape': torch.Size([64, 64]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0, 5]},
            'decoder_attention_mask': {
                'shape': torch.Size([64, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [5]},
            'decoder_input_ids': {
                'shape': torch.Size([64, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0, 5]},
            'input_ids': {
                'shape': torch.Size([64, 64]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0]},
            'labels': {
                'shape': torch.Size([64, 4]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [7]}},
        'model_outputs': {
            'T5ForConditionalGeneration/torch.nn.functional::cross_entropy_780': {
                'shape': torch.Size([1]),
                'dtype': torch.float32,
                'is_batched': False,
                'created_by': 7}},
        'stages': {
            0: {
                'stage_cls': Partition0,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([64, 64]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_input_ids': {
                        'shape': torch.Size([64, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'input_ids': {
                        'shape': torch.Size([64, 64]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::size_408': {
                        'shape': torch.Size([2]),
                        'dtype': torch.Size,
                        'req_grad': False,
                        'is_batched': False,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/Parameter[shared_embed_weight]': {
                        'shape': torch.Size([32100, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_1': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___79': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___81': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]}},
                'devices': ['cpu' if DEBUG else 'cuda:0'],
                'stage_depth': 7},
            1: {
                'stage_cls': Partition1,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_1': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___79': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___81': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_2': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [2]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___139': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___141': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]}},
                'devices': ['cpu' if DEBUG else 'cuda:1'],
                'stage_depth': 6},
            2: {
                'stage_cls': Partition2,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_2': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___139': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___141': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_3': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [3]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___199': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___201': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]}},
                'devices': ['cpu' if DEBUG else 'cuda:2'],
                'stage_depth': 5},
            3: {
                'stage_cls': Partition3,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_3': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___199': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___201': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_4': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___259': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___261': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]}},
                'devices': ['cpu' if DEBUG else 'cuda:3'],
                'stage_depth': 4},
            4: {
                'stage_cls': Partition4,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_4': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___259': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___261': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_5': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___319': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___321': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]}},
                'devices': ['cpu' if DEBUG else 'cuda:4'],
                'stage_depth': 3},
            5: {
                'stage_cls': Partition5,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([64, 64]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_attention_mask': {
                        'shape': torch.Size([64, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_input_ids': {
                        'shape': torch.Size([64, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::size_408': {
                        'shape': torch.Size([2]),
                        'dtype': torch.Size,
                        'req_grad': False,
                        'is_batched': False,
                        'created_by': 0},
                    'T5ForConditionalGeneration/Parameter[shared_embed_weight]': {
                        'shape': torch.Size([32100, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19_5': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___319': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___321': {
                        'shape': torch.Size([64, 32, 64, 64]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440_6': {
                        'shape': torch.Size([64, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448_6': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___460': {
                        'shape': torch.Size([64, 4, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___462': {
                        'shape': torch.Size([64, 32, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___464': {
                        'shape': torch.Size([64, 32, 4, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [6]}},
                'devices': ['cpu' if DEBUG else 'cuda:5'],
                'stage_depth': 2},
            6: {
                'stage_cls': Partition6,
                'inputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440_6': {
                        'shape': torch.Size([64, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448_6': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___460': {
                        'shape': torch.Size([64, 4, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___462': {
                        'shape': torch.Size([64, 32, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___464': {
                        'shape': torch.Size([64, 32, 4, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 5}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440_7': {
                        'shape': torch.Size([64, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448_7': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___616': {
                        'shape': torch.Size([64, 4, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___618': {
                        'shape': torch.Size([64, 32, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___620': {
                        'shape': torch.Size([64, 32, 4, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'used_by': [7]}},
                'devices': ['cpu' if DEBUG else 'cuda:6'],
                'stage_depth': 1},
            7: {
                'stage_cls': Partition7,
                'inputs': {
                    'labels': {
                        'shape': torch.Size([64, 4]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([64, 64, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440_7': {
                        'shape': torch.Size([64, 1, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448_7': {
                        'shape': torch.Size([64, 1, 1, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___616': {
                        'shape': torch.Size([64, 4, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___618': {
                        'shape': torch.Size([64, 32, 4, 4]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___620': {
                        'shape': torch.Size([64, 32, 4, 64]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': 6}},
                'outputs': {
                    'T5ForConditionalGeneration/torch.nn.functional::cross_entropy_780': {
                        'shape': torch.Size([1]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'used_by': [-1]}},
                'devices': ['cpu' if DEBUG else 'cuda:7'],
                'stage_depth': 0}}}
    
    
    # switching batch size
    batch_dim = config['batch_dim']
    for d in chain(config['model_inputs'].values(),config['model_outputs'].values()):
        if d['is_batched']:
            shape = d['shape']
            d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    for s in config['stages'].values():
        for d in chain(s['inputs'].values(),s['outputs'].values()):
            if d['is_batched']:
                shape = d['shape']
                d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    return config

class Partition0(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[0]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[2]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[3]',
        ]
    TENSORS = [
            'T5ForConditionalGeneration/Parameter[shared_embed_weight]',
        ]
    def __init__(self, layers, tensors, device='cuda:0'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.embed_tokens',
                        'l_1': 'encoder.dropout',
                        'l_2': 'encoder.block.0',
                        'l_3': 'encoder.block.1',
                        'l_4': 'encoder.block.2',
                        'l_5': 'encoder.block.3',
                        'p_0': 'shared_embed_weight'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[0] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[1] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[2] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[3] <=> self.l_5
        # T5ForConditionalGeneration/Parameter[shared_embed_weight] <=> self.p_0
        # input0 <=> attention_mask
        # input2 <=> decoder_input_ids
        # input3 <=> input_ids
        attention_mask, decoder_input_ids, input_ids = unflatten(args, self.input_structure)
        t_0 = decoder_input_ids.size()
        t_1 = input_ids.size()
        t_1 = t_1[-1]
        t_1 = input_ids.view(-1, t_1)
        t_1 = self.l_0(self.p_0, t_1)
        t_1 = self.l_1(t_1)
        t_2 = attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_2 = t_2.to(dtype=torch.float32)
        t_2 = 1.0 - t_2
        t_2 = t_2 * -10000.0
        t_1 = self.l_2(t_1, attention_mask=t_2, position_bias=None, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_3 = t_1[slice(None, 2, None)]
        t_3 = t_3[0]
        t_1 = t_1[2]
        t_1 = self.l_3(t_3, attention_mask=t_2, position_bias=t_1, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_3 = t_1[slice(None, 2, None)]
        t_3 = t_3[0]
        t_1 = t_1[2]
        t_1 = self.l_4(t_3, attention_mask=t_2, position_bias=t_1, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_3 = t_1[slice(None, 2, None)]
        t_3 = t_3[0]
        t_1 = t_1[2]
        t_1 = self.l_5(t_3, attention_mask=t_2, position_bias=t_1, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_3 = t_1[slice(None, 2, None)]
        t_3 = t_3[0]
        t_1 = t_1[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::size_408
        # T5ForConditionalGeneration/Parameter[shared_embed_weight]
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___79
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___81
        return list(flatten((t_0, self.p_0, t_2, t_3, t_1)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition1(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[4]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[5]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[6]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[7]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:1'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.4',
                        'l_1': 'encoder.block.5',
                        'l_2': 'encoder.block.6',
                        'l_3': 'encoder.block.7'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[4] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[5] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[6] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[7] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___79 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___81 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_3(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___139
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___141
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition2(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[8]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[9]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[10]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[11]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:2'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.8',
                        'l_1': 'encoder.block.9',
                        'l_2': 'encoder.block.10',
                        'l_3': 'encoder.block.11'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[8] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[9] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[10] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[11] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___139 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___141 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_3(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___199
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___201
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition3(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[12]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[13]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[14]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[15]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:3'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.12',
                        'l_1': 'encoder.block.13',
                        'l_2': 'encoder.block.14',
                        'l_3': 'encoder.block.15'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[12] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[13] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[14] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[15] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___199 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___201 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_3(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___259
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___261
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition4(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[16]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[17]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[18]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[19]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:4'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.16',
                        'l_1': 'encoder.block.17',
                        'l_2': 'encoder.block.18',
                        'l_3': 'encoder.block.19'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[16] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[17] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[18] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[19] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___259 <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___261 <=> x2
        x0, x1, x2 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x1, attention_mask=x0, position_bias=x2, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_3(t_1, attention_mask=x0, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___319
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___321
        return list(flatten((x0, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition5(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[20]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[21]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[22]',
            'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[23]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[0]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:5'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'encoder.block.20',
                        'l_1': 'encoder.block.21',
                        'l_2': 'encoder.block.22',
                        'l_3': 'encoder.block.23',
                        'l_4': 'encoder.final_layer_norm',
                        'l_5': 'encoder.dropout',
                        'l_6': 'decoder.embed_tokens',
                        'l_7': 'decoder.dropout',
                        'l_8': 'decoder.block.0'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[20] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[21] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[22] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[23] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens] <=> self.l_6
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_7
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[0] <=> self.l_8
        # input0 <=> attention_mask
        # input1 <=> decoder_attention_mask
        # input2 <=> decoder_input_ids
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::size_408 <=> x0
        # T5ForConditionalGeneration/Parameter[shared_embed_weight] <=> x1
        # T5ForConditionalGeneration/T5Stack[encoder]/Tensor::__mul___19 <=> x2
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___319 <=> x3
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___321 <=> x4
        attention_mask, decoder_attention_mask, decoder_input_ids, x0, x1, x2, x3, x4 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x2, position_bias=x4, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_1(t_1, attention_mask=x2, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_2(t_1, attention_mask=x2, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_0 = t_0[2]
        t_0 = self.l_3(t_1, attention_mask=x2, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, use_cache=False, output_attentions=False)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_1 = self.l_4(t_1)
        t_0 = t_0[2]
        t_1 = self.l_5(t_1)
        t_2 = x0[-1]
        t_2 = decoder_input_ids.view(-1, t_2)
        t_2 = self.l_6(x1, t_2)
        t_2 = self.l_7(t_2)
        t_3 = x0[0]
        t_4 = x0[1]
        t_5 = torch.arange(t_4, device=self.device)
        t_6 = t_5[(None, None, slice(None, None, None))]
        t_4 = t_6.repeat(t_3, t_4, 1)
        t_5 = t_5[(None, slice(None, None, None), None)]
        t_5 = t_4 <= t_5
        t_4 = decoder_attention_mask.dtype
        t_4 = t_5.to(t_4)
        t_4 = t_4[(slice(None, None, None), None, slice(None, None, None), slice(None, None, None))]
        t_5 = decoder_attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_5 = t_4 * t_5
        t_5 = t_5.to(dtype=torch.float32)
        t_5 = 1.0 - t_5
        t_5 = t_5 * -10000.0
        t_4 = attention_mask[(slice(None, None, None), None, None, slice(None, None, None))]
        t_4 = t_4.to(dtype=torch.float32)
        t_4 = 1.0 - t_4
        t_4 = t_4 * -1000000000.0
        t_2 = self.l_8(t_2, attention_mask=t_5, position_bias=None, encoder_attention_mask=t_4, encoder_decoder_position_bias=None, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=t_1)
        t_3 = t_2[slice(None, 2, None)]
        t_3 = t_3[0]
        t_6 = t_2[2]
        t_2 = t_2[3]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___460
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___462
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___464
        return list(flatten((t_1, t_5, t_4, t_3, t_6, t_2)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition6(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[2]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[3]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[4]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[5]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[6]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[7]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[8]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[9]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[10]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[11]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[12]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:6'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.block.1',
                        'l_1': 'decoder.block.2',
                        'l_2': 'decoder.block.3',
                        'l_3': 'decoder.block.4',
                        'l_4': 'decoder.block.5',
                        'l_5': 'decoder.block.6',
                        'l_6': 'decoder.block.7',
                        'l_7': 'decoder.block.8',
                        'l_8': 'decoder.block.9',
                        'l_9': 'decoder.block.10',
                        'l_10': 'decoder.block.11',
                        'l_11': 'decoder.block.12'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[1] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[2] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[3] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[4] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[5] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[6] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[7] <=> self.l_6
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[8] <=> self.l_7
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[9] <=> self.l_8
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[10] <=> self.l_9
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[11] <=> self.l_10
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[12] <=> self.l_11
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___460 <=> x3
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___462 <=> x4
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___464 <=> x5
        x0, x1, x2, x3, x4, x5 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x1, position_bias=x4, encoder_attention_mask=x2, encoder_decoder_position_bias=x5, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_1(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_2(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_3(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_4(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_5(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_6(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_7(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_8(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_9(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_10(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_11(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        # Returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___616
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___618
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___620
        return list(flatten((x0, x1, x2, t_2, t_1, t_0)))

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


class Partition7(nn.Module):
    LAYER_SCOPES = [
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[13]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[14]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[15]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[16]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[17]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[18]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[19]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[20]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[21]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[22]',
            'T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[23]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/Linear[lm_head]',
        ]
    TENSORS = [
        ]
    def __init__(self, layers, tensors, device='cuda:7'):
        super().__init__()

        # Initialize partition layers
        for idx, layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}' ,layers[layer_scope])

        # Initialize partition tensors (params and buffs)
        b = p = 0
        for tensor_scope in self.TENSORS:
            tensor = tensors[tensor_scope]
            if isinstance(tensor, nn.Parameter):
                self.register_parameter(f'p_{p}', tensor)
                p += 1
            else:
                self.register_buffer(f'b_{b}', tensor)
                b += 1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1, 1]
        self.lookup = {'l_0': 'decoder.block.13',
                        'l_1': 'decoder.block.14',
                        'l_2': 'decoder.block.15',
                        'l_3': 'decoder.block.16',
                        'l_4': 'decoder.block.17',
                        'l_5': 'decoder.block.18',
                        'l_6': 'decoder.block.19',
                        'l_7': 'decoder.block.20',
                        'l_8': 'decoder.block.21',
                        'l_9': 'decoder.block.22',
                        'l_10': 'decoder.block.23',
                        'l_11': 'decoder.final_layer_norm',
                        'l_12': 'decoder.dropout',
                        'l_13': 'lm_head'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[13] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[14] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[15] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[16] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[17] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[18] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[19] <=> self.l_6
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[20] <=> self.l_7
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[21] <=> self.l_8
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[22] <=> self.l_9
        # T5ForConditionalGeneration/T5Stack[decoder]/ModuleList[block]/T5Block[23] <=> self.l_10
        # T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm] <=> self.l_11
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_12
        # T5ForConditionalGeneration/Linear[lm_head] <=> self.l_13
        # input4 <=> labels
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___440 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Tensor::__mul___448 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___616 <=> x3
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___618 <=> x4
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___620 <=> x5
        labels, x0, x1, x2, x3, x4, x5 = unflatten(args, self.input_structure)
        t_0 = self.l_0(x3, attention_mask=x1, position_bias=x4, encoder_attention_mask=x2, encoder_decoder_position_bias=x5, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_1(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_2(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_3(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_4(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_5(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_6(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_7(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_8(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_9(t_1, attention_mask=x1, position_bias=t_2, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_2 = t_0[slice(None, 2, None)]
        t_2 = t_2[0]
        t_1 = t_0[2]
        t_0 = t_0[3]
        t_0 = self.l_10(t_2, attention_mask=x1, position_bias=t_1, encoder_attention_mask=x2, encoder_decoder_position_bias=t_0, layer_head_mask=None, encoder_layer_head_mask=None, past_key_value=None, output_attentions=False, use_cache=False, encoder_hidden_states=x0)
        t_1 = t_0[slice(None, 2, None)]
        t_1 = t_1[0]
        t_1 = self.l_11(t_1)
        t_2 = t_0[2]
        t_0 = t_0[3]
        t_1 = self.l_12(t_1)
        t_1 = t_1 * 0.03125
        t_1 = self.l_13(t_1)
        t_3 = t_1.size(-1)
        t_3 = t_1.view(-1, t_3)
        t_1 = labels.view(-1)
        t_1 = torch.nn.functional.cross_entropy(t_3, t_1, weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
        # Returning:
        # T5ForConditionalGeneration/torch.nn.functional::cross_entropy_780
        return (t_1,)

    def state_dict(self, *args, **kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self, *args, **kwargs)

    def load_state_dict(self, *args, **kwargs):
        return load_state_dict(self, *args, **kwargs)

    def named_parameters(self, *args, **kwargs):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self, *args, **kwargs)

    def named_buffers(self, *args, **kwargs):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self, *args, **kwargs)

    def cpu(self):
        return cpu(self)

    def cuda(self, device=None):
        return cuda(self, device=device)

    def to(self, *args, **kwargs):
        return to(self, *args, **kwargs)


def traverse_model(module: nn.Module, depth: int, prefix: Optional[str] = None,
                   basic_blocks: Tuple[Type[nn.Module]] = (), full: bool = False) -> Iterator[
    Tuple[nn.Module, str, nn.Module, Optional[bool]]]:
    """
    iterate over model layers yielding the layer,layer_scope,encasing_module
    Parameters:
    -----------
    model:
        the model to iterate over
    depth:
        how far down in the model tree to go
    basic_blocks:
        a list of modules that if encountered will not be broken down
    full:
        whether to yield only layers specified by the depth and basic_block options or to yield all layers
    """
    if prefix is None:
        prefix = type(module).__name__

    for name, sub_module in module.named_children():
        scope = prefix + "/" + type(sub_module).__name__ + f"[{name}]"
        if len(list(sub_module.children())) == 0 or isinstance(sub_module, tuple(basic_blocks)) or depth == 0:
            if full:
                # TODO:
                # is_explicit_block_limit = len(list(sub_module.children())) != 0 and (isinstance(sub_module, tuple(basic_blocks)) or depth == 0)
                yield sub_module, scope, module, True

            else:
                yield sub_module, scope, module
        else:
            if full:
                yield sub_module, scope, module, False
            yield from traverse_model(sub_module, depth - 1, scope, basic_blocks, full)


def layerDict(model: nn.Module, depth=1000, basic_blocks=()) -> Dict[str, nn.Module]:
    return {s: l for l, s, _ in traverse_model(model, depth, basic_blocks=basic_blocks)}


def traverse_params_buffs(module: nn.Module, prefix: Optional[str] = None) -> Iterator[Tuple[torch.tensor, str]]:
    """
    iterate over model's buffers and parameters yielding obj,obj_scope

    Parameters:
    -----------
    model:
        the model to iterate over
    """
    if prefix is None:
        prefix = type(module).__name__

    # params
    for param_name, param in module.named_parameters(recurse=False):
        param_scope = f"{prefix}/{type(param).__name__}[{param_name}]"
        yield param, param_scope

    # buffs
    for buffer_name, buffer in module.named_buffers(recurse=False):
        buffer_scope = f"{prefix}/{type(buffer).__name__}[{buffer_name}]"
        yield buffer, buffer_scope

    # recurse
    for name, sub_module in module.named_children():
        yield from traverse_params_buffs(sub_module, prefix + "/" + type(sub_module).__name__ + f"[{name}]")


def tensorDict(model: nn.Module) -> OrderedDict[str, Tensor]:
    return collections.OrderedDict((s, t) for t, s in traverse_params_buffs(model))


def move_tensors(ts, device):
    def move(t):
        if isinstance(t, (nn.Module, Tensor)):
            return t.to(device)
        return t

    return nested_map(move, ts)


def nested_map(func, ts, full=False):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        return func(ts)
    elif isinstance(ts, (list, tuple, set)):
        return type(ts)(nested_map(func, t, full=full) for t in ts)
    elif isinstance(ts, dict):
        return {k: nested_map(func, v, full=full) for k, v in ts.items()}
    elif isinstance(ts, slice) and full:
        start = nested_map(func, ts.start, full=full)
        stop = nested_map(func, ts.stop, full=full)
        step = nested_map(func, ts.step, full=full)
        return slice(start, stop, step)
    return func(ts)


def flatten(ts):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        yield ts
    elif isinstance(ts, (list, tuple, set)):
        yield from chain(*[flatten(t) for t in ts])
    elif isinstance(ts, dict):
        yield from chain(*[flatten(t) for k, t in sorted(ts.items(), key=lambda t: t[0])])
    else:
        yield ts


def unflatten(xs, structure):
    return _unflatten(xs, structure)[0]


def _unflatten(xs, structure):
    if isinstance(structure, torch.Size):
        # torch.Size is subclass of tuple which is stupid
        return xs[0], 1

    if not isinstance(structure, (list, tuple, set, dict)):
        return xs[0], 1

    if isinstance(structure, (list, tuple, set)):
        offset = 0
        elements = []
        for s in structure:
            e, n = _unflatten(xs[offset:], s)
            elements.append(e)
            offset += n

        return type(structure)(elements), offset

    assert isinstance(structure, dict)
    offset = 0
    elements = dict()
    for k, v in sorted(structure.items(), key=lambda t: t[0]):
        e, n = _unflatten(xs[offset:], v)
        elements[k] = e
        offset += n

    return elements, offset


def state_dict(partition, *args, **kwargs):
    # we return the state dict of this part as it should be in the original model
    state = nn.Module.state_dict(partition, *args, **kwargs)
    lookup = partition.lookup
    result = dict()
    for k, v in state.items():
        if k in lookup:
            result[lookup[k]] = v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            result[new_k] = v
    return result


def load_state_dict(partition, state_dict, strict=True):
    reverse_lookup = {v: k for k, v in partition.lookup.items()}
    device = partition.device
    keys = list(partition.state_dict(None).keys())
    new_state = dict()
    for k in keys:
        if k in reverse_lookup:
            new_state[reverse_lookup[k]] = state_dict[k].to(device)
            continue
        idx = k.rfind(".")
        to_replace = k[:idx]
        if to_replace in reverse_lookup:
            key = reverse_lookup[to_replace] + k[idx:]
            new_state[key] = state_dict[k].to(device)
    nn.Module.load_state_dict(partition, new_state, strict=strict)


def named_buffers(partition, prefix='', recurse=True):
    # we return the named buffers of this part as it should be in the original model
    params = nn.Module.named_buffers(partition, prefix=prefix, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def named_parameters(partition, prefix='', recurse=True):
    # we return the named parameters of this part as it should be in the original model
    params = nn.Module.named_parameters(partition, prefix=prefix, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield lookup[k], v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield new_k, v


def cpu(partition):
    partition.device = torch.device('cpu')
    return nn.Module.cpu(partition)


def cuda(partition, device=None):
    if device is None:
        device = torch.cuda.current_device()
    partition.device = torch.device(device)
    return nn.Module.cuda(partition, partition.device)


def to(partition, *args, **kwargs):
    device = None
    if 'device' in kwargs:
        device = kwargs['device']
    elif 'tensor' in kwargs:
        device = kwargs['tensor'].device
    if args:
        if isinstance(args[0], (torch.device, int, str)):
            device = args[0]
        if torch.is_tensor(args[0]):
            device = args[0].device
    if not (device is None):
        partition.device = torch.device(device)
    return nn.Module.to(partition, *args, **kwargs)

model_args = {'model_name_or_path': 't5-3b', 'max_seq_length': 64, 'answer_max_seq_length': 4, 'stateless_tied': True, 'lmhead': True, 'precompute_masks': False}

def layer_graph_t5_3b_tied_lmheads_64_4_8p_bw12_squad1_pipedream():
    return dict(model_type='t5_stateless',
                model_name_or_path='t5-3b',
                do_lower_case=False,
                output_past=False,
                stateless_tied=True,
                explicitly_set_dict={'return_dict': False, 'use_cache': False, 'output_only': True, 'output_attentions': False, 'precompute_masks': False, 'output_hidden_states': False},
                do_resize_token_embedding=True,
                )
    
"""analysis summary
-I- Printing Report
warnings:
Partition0 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___81 is not contiguous!
Partition1 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___141 is not contiguous!
Partition2 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___201 is not contiguous!
Partition3 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___261 is not contiguous!
Partition4 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___321 is not contiguous!
Partition5 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___462 is not contiguous!
Partition6 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___618 is not contiguous!
Number of nodes in Computation Graph: 781
Number of stages: 8
backward times include recomputation
Analysis for async_pipeline=True: last partition will not do recomputation.

Stage parameter count:
 {0: 234206208,
 1: 201334784,
 2: 201334784,
 3: 201334784,
 4: 201334784,
 5: 268448768,
 6: 805343232,
 7: 771102720,
 'total': 2884440064}

GPU parameter count:
 Number of Model Parameters 2884.4M
{'total': 2884440064}

real times are based on real measurements of execution time (with communication) of generated partitions ms
forward {0: 169.76, 1: 156.98, 2: 157.08, 3: 157.05, 4: 157.28, 5: 163.82, 6: 120.93, 7: 110.25}
backward {0: 447.08, 1: 447.72, 2: 447.48, 3: 447.47, 4: 447.91, 5: 489.25, 6: 344.78, 7: 207.99}

Analysis for T = (1-R)fwd + R*bwd:

Pipeline Slowdown: (compared to sequential execution with no communication, and same recompute policy)
forward 1.173
backward 1.206

Expected utilization by partition
forward {0: 0.91, 1: 0.9, 2: 0.91, 3: 0.91, 4: 0.91, 5: 0.96, 6: 0.7, 7: 0.65}
backward {0: 0.91, 1: 0.91, 2: 0.9, 3: 0.9, 4: 0.91, 5: 0.97, 6: 0.7, 7: 0.43}

worstcase: bwd: 489.252 fwd: 169.759
Expected speedup for 8 partitions is: 6.679
Assuming bandwidth of 12 GBps between GPUs

communication volumes size of activations of each partition
0: input size:'0.00 MB', recieve_time:'0.00 ms', out:'181.83 MB', send time:'15.15 ms'
1: input size:'50.35 MB', recieve_time:'4.20 ms', out:'50.35 MB', send time:'4.20 ms'
2: input size:'50.35 MB', recieve_time:'4.20 ms', out:'50.35 MB', send time:'4.20 ms'
3: input size:'50.35 MB', recieve_time:'4.20 ms', out:'50.35 MB', send time:'4.20 ms'
4: input size:'50.35 MB', recieve_time:'4.20 ms', out:'50.35 MB', send time:'4.20 ms'
5: input size:'181.83 MB', recieve_time:'15.15 ms', out:'20.07 MB', send time:'1.67 ms'
6: input size:'20.07 MB', recieve_time:'1.67 ms', out:'20.07 MB', send time:'1.67 ms'
7: input size:'20.07 MB', recieve_time:'1.67 ms', out:'0.00 MB', send time:'0.00 ms'

Compuatation Communication ratio (comp/(comp+comm)):
forward {0: 0.91, 1: 0.97, 2: 0.97, 3: 0.97, 4: 0.97, 5: 0.99, 6: 0.99, 7: 1.0} 
backward {0: 1.0, 1: 0.99, 2: 0.99, 3: 0.99, 4: 0.99, 5: 0.97, 6: 1.0, 7: 0.99}

Analysis for T = fwd + bwd:
 {'expected_compute_utilization': {0: 0.95,
                                  1: 0.94,
                                  2: 0.94,
                                  3: 0.94,
                                  4: 0.94,
                                  5: 1.0,
                                  6: 0.73,
                                  7: 0.5,
                                  'worstcase_std': 0.01},
 'pipeline_no_comm': {0: 601.69,
                      1: 596.31,
                      2: 596.17,
                      3: 596.13,
                      4: 596.8,
                      5: 636.25,
                      6: 462.36,
                      7: 316.57,
                      'worstcase': 636.25,
                      'worstcase_std': 3.39},
 'pipeline_vs_seq_no_comm': 5.32,
 'pipeline_with_non_parallel_comm': {0: 616.84,
                                     1: 604.7,
                                     2: 604.56,
                                     3: 604.52,
                                     4: 605.19,
                                     5: 653.08,
                                     6: 465.7,
                                     7: 318.24,
                                     'worstcase': 653.08},
 'seq_no_comm_no_recomp': {0: 451.73,
                           1: 447.82,
                           2: 448.52,
                           3: 448.44,
                           4: 448.03,
                           5: 476.34,
                           6: 345.62,
                           7: 321.26}}

expected_speedup_compared_to_seq_no_recomp_no_comm: 5.141
Analysis max cuda memory used 6.62GB
"""