"""AutoGenerated with:
python partitioning_script.py --partitioning_task t5 --t5_task squad1 --lmhead --n_iter 10 --n_partitions 8 --analysis_batch_size 1 --partitioning_batch_size 1 --precompute_masks --stateless_tied --model_name_or_path t5-3b --save_memory_mode --max_seq_length 128 --answer_max_seq_length 16 --basic_blocks T5Block --constraint memory --objective stage_time --profiles_cache_name t5_3b_cache
"""
import math
import torch.functional
import torch
import torch.nn.functional
from torch import Tensor
import torch.nn as nn
from itertools import chain
from typing import Optional, Tuple, Iterator, Iterable, OrderedDict, Dict
import collections

from models.normal.NLP_models.stateless import StatelessEmbedding
from models.normal.NLP_models.modeling_t5 import T5LayerNorm
from models.normal.NLP_models.modeling_t5 import T5Block
from torch.nn.modules.loss import CrossEntropyLoss
from torch.nn.modules.linear import Linear
from torch.nn.modules.dropout import Dropout
# this is an auto generated file do not edit unless you know what you are doing


# partition adjacency
# model inputs {0, 1, 2, 3, 4, 5, 6, 7}
# partition 0 {'inputs': {'attention_mask', 'input_ids', 'decoder_input_ids'}, 'outputs': {1, 2, 3}}
# partition 1 {'inputs': {'attention_mask', 0}, 'outputs': {2}}
# partition 2 {'inputs': {'attention_mask', 0, 1}, 'outputs': {3}}
# partition 3 {'inputs': {0, 2, 'decoder_attention_mask', 'inverted_encoder_attention_mask', 'attention_mask'}, 'outputs': {4, 5, 6, 7}}
# partition 4 {'inputs': {3, 'decoder_attention_mask', 'inverted_encoder_attention_mask'}, 'outputs': {5}}
# partition 5 {'inputs': {3, 4, 'decoder_attention_mask', 'inverted_encoder_attention_mask'}, 'outputs': {6}}
# partition 6 {'inputs': {5, 3, 'decoder_attention_mask', 'inverted_encoder_attention_mask'}, 'outputs': {7}}
# partition 7 {'inputs': {3, 'decoder_attention_mask', 6, 'inverted_encoder_attention_mask', 'lm_labels'}, 'outputs': {'output'}}
# model outputs {7}


def create_pipeline_configuration(DEBUG=False, batch_size=1):
    config = {
        'batch_dim': 0,
        'depth': 10000,
        'basic_blocks': (StatelessEmbedding,T5LayerNorm,T5Block,CrossEntropyLoss,Linear,Dropout),
        'model_inputs': {
            'attention_mask': {
                'shape': torch.Size([1, 1, 1, 128]),
                'dtype': torch.float32,
                'is_batched': True,
                'used_by': [0, 1, 2, 3]},
            'decoder_attention_mask': {
                'shape': torch.Size([1, 1, 16, 16]),
                'dtype': torch.float32,
                'is_batched': True,
                'used_by': [3, 4, 5, 6, 7]},
            'decoder_input_ids': {
                'shape': torch.Size([1, 16]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0]},
            'input_ids': {
                'shape': torch.Size([1, 128]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [0]},
            'inverted_encoder_attention_mask': {
                'shape': torch.Size([1, 1, 1, 128]),
                'dtype': torch.float32,
                'is_batched': True,
                'used_by': [3, 4, 5, 6, 7]},
            'lm_labels': {
                'shape': torch.Size([1, 16]),
                'dtype': torch.int64,
                'is_batched': True,
                'used_by': [7]}},
        'model_outputs': {
            'T5ForConditionalGeneration/CrossEntropyLoss[lm_loss]': {
                'shape': torch.Size([1]),
                'dtype': torch.float32,
                'is_batched': False,
                'created_by': 7}},
        'stages': {
            0: {
                'stage_cls': Partition0,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_input_ids': {
                        'shape': torch.Size([1, 16]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'input_ids': {
                        'shape': torch.Size([1, 128]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_1': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [1]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]}},
                'devices': ['cpu' if DEBUG else 'cuda:0']},
            1: {
                'stage_cls': Partition1,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_1': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_2': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [2]}},
                'devices': ['cpu' if DEBUG else 'cuda:1']},
            2: {
                'stage_cls': Partition2,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_2': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 1}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_3': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [3]}},
                'devices': ['cpu' if DEBUG else 'cuda:2']},
            3: {
                'stage_cls': Partition3,
                'inputs': {
                    'attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'decoder_attention_mask': {
                        'shape': torch.Size([1, 1, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'inverted_encoder_attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_3': {
                        'shape': torch.Size([1, 32, 128, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20]': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 2},
                    'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 0}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_4': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_4': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_4': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [4]}},
                'devices': ['cpu' if DEBUG else 'cuda:3']},
            4: {
                'stage_cls': Partition4,
                'inputs': {
                    'decoder_attention_mask': {
                        'shape': torch.Size([1, 1, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'inverted_encoder_attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_4': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_4': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_4': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 3}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_5': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_5': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_5': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [5]}},
                'devices': ['cpu' if DEBUG else 'cuda:4']},
            5: {
                'stage_cls': Partition5,
                'inputs': {
                    'decoder_attention_mask': {
                        'shape': torch.Size([1, 1, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'inverted_encoder_attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_5': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_5': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_5': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 4}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_6': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_6': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [6]}},
                'devices': ['cpu' if DEBUG else 'cuda:5']},
            6: {
                'stage_cls': Partition6,
                'inputs': {
                    'decoder_attention_mask': {
                        'shape': torch.Size([1, 1, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'inverted_encoder_attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_6': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_6': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_6': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 5}},
                'outputs': {
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_7': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_7': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'used_by': [7]}},
                'devices': ['cpu' if DEBUG else 'cuda:6']},
            7: {
                'stage_cls': Partition7,
                'inputs': {
                    'decoder_attention_mask': {
                        'shape': torch.Size([1, 1, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'inverted_encoder_attention_mask': {
                        'shape': torch.Size([1, 1, 1, 128]),
                        'dtype': torch.float32,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'lm_labels': {
                        'shape': torch.Size([1, 16]),
                        'dtype': torch.int64,
                        'req_grad': False,
                        'is_batched': True,
                        'created_by': -1},
                    'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]_7': {
                        'shape': torch.Size([1, 128, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_7': {
                        'shape': torch.Size([1, 32, 16, 16]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_7': {
                        'shape': torch.Size([1, 32, 16, 128]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6},
                    'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18]': {
                        'shape': torch.Size([1, 16, 1024]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': True,
                        'created_by': 6}},
                'outputs': {
                    'T5ForConditionalGeneration/CrossEntropyLoss[lm_loss]': {
                        'shape': torch.Size([1]),
                        'dtype': torch.float32,
                        'req_grad': True,
                        'is_batched': False,
                        'used_by': [-1]}},
                'devices': ['cpu' if DEBUG else 'cuda:7']}}}
    
    
    # switching batch size
    batch_dim = config['batch_dim']
    for d in chain(config['model_inputs'].values(),config['model_outputs'].values()):
        if d['is_batched']:
            shape = d['shape']
            d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    for s in config['stages'].values():
        for d in chain(s['inputs'].values(),s['outputs'].values()):
            if d['is_batched']:
                shape = d['shape']
                d['shape'] = torch.Size(shape[:batch_dim] + (batch_size,) + shape[batch_dim+1:])
    
    return config

class Partition0(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[0]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[2]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[3]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[4]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[5]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6]',
            'T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
        ]
    TENSORS=[
            'T5ForConditionalGeneration/Parameter[shared_embed_weight]',
        ]
    def __init__(self, layers, tensors, device='cuda:0'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = { 'l_0': 'encoder.embed_tokens',
                        'l_1': 'encoder.dropout',
                        'l_2': 'encoder.0',
                        'l_3': 'encoder.1',
                        'l_4': 'encoder.2',
                        'l_5': 'encoder.3',
                        'l_6': 'encoder.4',
                        'l_7': 'encoder.5',
                        'l_8': 'encoder.6',
                        'l_9': 'decoder.embed_tokens',
                        'l_10': 'decoder.dropout',
                        'p_0': 'shared_embed_weight'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/StatelessEmbedding[embed_tokens] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[0] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[1] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[2] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[3] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[4] <=> self.l_6
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[5] <=> self.l_7
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6] <=> self.l_8
        # T5ForConditionalGeneration/T5Stack[decoder]/StatelessEmbedding[embed_tokens] <=> self.l_9
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_10
        # T5ForConditionalGeneration/Parameter[shared_embed_weight] <=> self.p_0
        # input0 <=> attention_mask
        # input2 <=> decoder_input_ids
        # input3 <=> input_ids

        # moving inputs to current device no op if already on the correct device
        attention_mask, decoder_input_ids, input_ids = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = input_ids.size()
        t_0 = t_0[-1]
        t_0 = input_ids.view(-1, t_0)
        t_0 = self.l_0(self.p_0, t_0)
        t_0 = self.l_1(t_0)
        t_0 = self.l_2(t_0, attention_mask=attention_mask, position_bias=None, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = t_0[0]
        t_0 = t_0[1]
        t_1 = self.l_3(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = self.l_4(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = self.l_5(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = self.l_6(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = self.l_7(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_1 = self.l_8(t_1, attention_mask=attention_mask, position_bias=t_0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_2 = decoder_input_ids.size()
        t_2 = t_2[-1]
        t_2 = decoder_input_ids.view(-1, t_2)
        t_2 = self.l_9(self.p_0, t_2)
        t_2 = self.l_10(t_2)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6]
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]
        return list(flatten((t_0, t_1, t_2)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition1(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[7]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[8]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[9]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[10]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[11]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[12]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:1'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = { 'l_0': 'encoder.7',
                        'l_1': 'encoder.8',
                        'l_2': 'encoder.9',
                        'l_3': 'encoder.10',
                        'l_4': 'encoder.11',
                        'l_5': 'encoder.12',
                        'l_6': 'encoder.13'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[7] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[8] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[9] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[10] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[11] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[12] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13] <=> self.l_6
        # input0 <=> attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[6] <=> x1

        # moving inputs to current device no op if already on the correct device
        attention_mask, x0, x1 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x1, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_1(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_2(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_3(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_4(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_5(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_6(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13]
        return list(flatten((x0, t_0)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition2(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[14]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[15]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[16]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[17]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[18]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[19]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:2'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1]
        self.lookup = { 'l_0': 'encoder.14',
                        'l_1': 'encoder.15',
                        'l_2': 'encoder.16',
                        'l_3': 'encoder.17',
                        'l_4': 'encoder.18',
                        'l_5': 'encoder.19',
                        'l_6': 'encoder.20'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[14] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[15] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[16] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[17] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[18] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[19] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20] <=> self.l_6
        # input0 <=> attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[13] <=> x1

        # moving inputs to current device no op if already on the correct device
        attention_mask, x0, x1 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x1, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_1(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_2(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_3(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_4(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_5(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_6(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20]
        return list(flatten((x0, t_0)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition3(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[21]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[22]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5Block[23]',
            'T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[0]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[1]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[2]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:3'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = { 'l_0': 'encoder.21',
                        'l_1': 'encoder.22',
                        'l_2': 'encoder.23',
                        'l_3': 'encoder.final_layer_norm',
                        'l_4': 'encoder.dropout',
                        'l_5': 'decoder.0',
                        'l_6': 'decoder.1',
                        'l_7': 'decoder.2',
                        'l_8': 'decoder.3'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[21] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[22] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[23] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[encoder]/T5LayerNorm[final_layer_norm] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[0] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[1] <=> self.l_6
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[2] <=> self.l_7
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3] <=> self.l_8
        # input0 <=> attention_mask
        # input1 <=> decoder_attention_mask
        # input4 <=> inverted_encoder_attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22 <=> x0
        # T5ForConditionalGeneration/T5Stack[encoder]/T5Block[20] <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> x2

        # moving inputs to current device no op if already on the correct device
        attention_mask, decoder_attention_mask, inverted_encoder_attention_mask, x0, x1, x2 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x1, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_1(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_2(t_0, attention_mask=attention_mask, position_bias=x0, encoder_hidden_states=None, encoder_attention_mask=None, encoder_decoder_position_bias=None)
        t_0 = self.l_3(t_0)
        t_0 = self.l_4(t_0)
        t_1 = self.l_5(x2, attention_mask=decoder_attention_mask, position_bias=None, encoder_hidden_states=t_0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=None)
        t_2 = t_1[0]
        t_3 = t_1[1]
        t_1 = t_1[2]
        t_2 = self.l_6(t_2, attention_mask=decoder_attention_mask, position_bias=t_3, encoder_hidden_states=t_0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=t_1)
        t_2 = self.l_7(t_2, attention_mask=decoder_attention_mask, position_bias=t_3, encoder_hidden_states=t_0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=t_1)
        t_2 = self.l_8(t_2, attention_mask=decoder_attention_mask, position_bias=t_3, encoder_hidden_states=t_0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=t_1)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3]
        return list(flatten((t_0, t_3, t_1, t_2)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition4(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[4]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[5]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[6]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[7]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:4'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = { 'l_0': 'decoder.4',
                        'l_1': 'decoder.5',
                        'l_2': 'decoder.6',
                        'l_3': 'decoder.7',
                        'l_4': 'decoder.8'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[4] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[5] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[6] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[7] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8] <=> self.l_4
        # input1 <=> decoder_attention_mask
        # input4 <=> inverted_encoder_attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[3] <=> x3

        # moving inputs to current device no op if already on the correct device
        decoder_attention_mask, inverted_encoder_attention_mask, x0, x1, x2, x3 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x3, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_1(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_2(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_3(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_4(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8]
        return list(flatten((x0, x1, x2, t_0)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition5(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[9]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[10]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[11]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[12]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:5'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = { 'l_0': 'decoder.9',
                        'l_1': 'decoder.10',
                        'l_2': 'decoder.11',
                        'l_3': 'decoder.12',
                        'l_4': 'decoder.13'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[9] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[10] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[11] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[12] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13] <=> self.l_4
        # input1 <=> decoder_attention_mask
        # input4 <=> inverted_encoder_attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[8] <=> x3

        # moving inputs to current device no op if already on the correct device
        decoder_attention_mask, inverted_encoder_attention_mask, x0, x1, x2, x3 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x3, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_1(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_2(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_3(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_4(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13]
        return list(flatten((x0, x1, x2, t_0)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition6(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[14]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[15]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[16]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[17]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:6'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1]
        self.lookup = { 'l_0': 'decoder.14',
                        'l_1': 'decoder.15',
                        'l_2': 'decoder.16',
                        'l_3': 'decoder.17',
                        'l_4': 'decoder.18'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[14] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[15] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[16] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[17] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18] <=> self.l_4
        # input1 <=> decoder_attention_mask
        # input4 <=> inverted_encoder_attention_mask
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[13] <=> x3

        # moving inputs to current device no op if already on the correct device
        decoder_attention_mask, inverted_encoder_attention_mask, x0, x1, x2, x3 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x3, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_1(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_2(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_3(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_4(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        # returning:
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout]
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18]
        return list(flatten((x0, x1, x2, t_0)))

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


class Partition7(nn.Module):
    LAYER_SCOPES=[
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[19]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[20]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[21]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[22]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5Block[23]',
            'T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm]',
            'T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout]',
            'T5ForConditionalGeneration/Linear[lm_head]',
            'T5ForConditionalGeneration/CrossEntropyLoss[lm_loss]',
        ]
    TENSORS=[
        ]
    def __init__(self, layers, tensors, device='cuda:7'):
        super().__init__()

        #initialize partition layers
        for idx,layer_scope in enumerate(self.LAYER_SCOPES):
            self.add_module(f'l_{idx}',layers[layer_scope])

        #initialize partition tensors
        b=p=0
        for tensor_scope in self.TENSORS:
            tensor=tensors[tensor_scope]
            if isinstance(tensor,nn.Parameter):
                self.register_parameter(f'p_{p}',tensor)
                p+=1
            else:
                self.register_buffer(f'b_{b}',tensor)
                b+=1

        self.device = torch.device(device)
        self.input_structure = [1, 1, 1, 1, 1, 1, 1]
        self.lookup = { 'l_0': 'decoder.19',
                        'l_1': 'decoder.20',
                        'l_2': 'decoder.21',
                        'l_3': 'decoder.22',
                        'l_4': 'decoder.23',
                        'l_5': 'decoder.final_layer_norm',
                        'l_6': 'decoder.dropout',
                        'l_7': 'lm_head',
                        'l_8': 'lm_loss'}
        self.to(self.device)

    def forward(self, *args):
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[19] <=> self.l_0
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[20] <=> self.l_1
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[21] <=> self.l_2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[22] <=> self.l_3
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[23] <=> self.l_4
        # T5ForConditionalGeneration/T5Stack[decoder]/T5LayerNorm[final_layer_norm] <=> self.l_5
        # T5ForConditionalGeneration/T5Stack[decoder]/Dropout[dropout] <=> self.l_6
        # T5ForConditionalGeneration/Linear[lm_head] <=> self.l_7
        # T5ForConditionalGeneration/CrossEntropyLoss[lm_loss] <=> self.l_8
        # input1 <=> decoder_attention_mask
        # input4 <=> inverted_encoder_attention_mask
        # input5 <=> lm_labels
        # T5ForConditionalGeneration/T5Stack[encoder]/Dropout[dropout] <=> x0
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130 <=> x1
        # T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132 <=> x2
        # T5ForConditionalGeneration/T5Stack[decoder]/T5Block[18] <=> x3

        # moving inputs to current device no op if already on the correct device
        decoder_attention_mask, inverted_encoder_attention_mask, lm_labels, x0, x1, x2, x3 = move_tensors(unflatten(args,self.input_structure), self.device)
        t_0 = self.l_0(x3, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_1(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_2(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_3(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_4(t_0, attention_mask=decoder_attention_mask, position_bias=x1, encoder_hidden_states=x0, encoder_attention_mask=inverted_encoder_attention_mask, encoder_decoder_position_bias=x2)
        t_0 = self.l_5(t_0)
        t_0 = self.l_6(t_0)
        t_0 = t_0 * 0.03125
        t_0 = self.l_7(t_0)
        t_1 = t_0.size(-1)
        t_1 = t_0.view(-1, t_1)
        t_0 = lm_labels.view(-1)
        t_0 = self.l_8(t_1, t_0)
        # returning:
        # T5ForConditionalGeneration/CrossEntropyLoss[lm_loss]
        return (t_0,)

    def state_dict(self,*args,**kwargs):
        # we return the state dict of this part as it should be in the original model
        return state_dict(self,*args,**kwargs)

    def load_state_dict(self, state):
        return load_state_dict(self,state)

    def named_parameters(self,recurse=True):
        # we return the named parameters of this part as it should be in the original model
        return named_parameters(self,recurse=recurse)

    def named_buffers(self,recurse=True):
        # we return the named buffers of this part as it should be in the original model
        return named_buffers(self,recurse=recurse)

    def cpu(self):
        return cpu(self)

    def cuda(self,device=None):
        return cuda(self,device=device)

    def to(self, *args, **kwargs):
        return to(self,*args,**kwargs)


def traverse_model(module: nn.Module, depth: int, prefix: Optional[str] = None,
                   basic_blocks: Tuple[nn.Module] = (), full: bool = False) -> Iterator[Tuple[nn.Module, str, nn.Module]]:
    '''
    iterate over model layers yielding the layer,layer_scope,encasing_module
    Parameters:
    -----------
    model:
        the model to iterate over
    depth:
        how far down in the model tree to go
    basic_blocks:
        a list of modules that if encountered will not be broken down
    full:
        whether to yield only layers specified by the depth and basick_block options or to yield all layers
    '''
    if prefix is None:
        prefix = type(module).__name__

    for name, sub_module in module.named_children():
        scope = prefix + "/" + type(sub_module).__name__ + f"[{name}]"
        if len(list(sub_module.children())) == 0 or isinstance(sub_module, tuple(basic_blocks)) or depth == 0:
            if full:
                yield sub_module, scope, module, True
            else:
                yield sub_module, scope, module
        else:
            if full:
                yield sub_module, scope, module, False
            yield from traverse_model(sub_module, depth - 1, scope, basic_blocks, full)


def layerDict(model: nn.Module, depth=1000, basic_blocks=()) -> Dict[str, nn.Module]:
    return {s: l for l, s, _ in traverse_model(model, depth, basic_blocks=basic_blocks)}


def traverse_params_buffs(module: nn.Module, prefix: Optional[str] = None) -> Iterator[Tuple[torch.tensor, str]]:
    '''
    iterate over model's buffers and parameters yielding obj,obj_scope

    Parameters:
    -----------
    model:
        the model to iterate over
    '''
    if prefix is None:
        prefix = type(module).__name__

    # params
    for param_name, param in module.named_parameters(recurse=False):
        param_scope = f"{prefix}/{type(param).__name__}[{param_name}]"
        yield param, param_scope

    # buffs
    for buffer_name, buffer in module.named_buffers(recurse=False):
        buffer_scope = f"{prefix}/{type(buffer).__name__}[{buffer_name}]"
        yield buffer, buffer_scope

    # recurse
    for name, sub_module in module.named_children():
        yield from traverse_params_buffs(sub_module, prefix + "/" + type(sub_module).__name__ + f"[{name}]")


def tensorDict(model: nn.Module) -> OrderedDict[str, Tensor]:
    return collections.OrderedDict((s, t)for t, s in traverse_params_buffs(model))


def move_tensors(ts, device):
    def move(t):
        if isinstance(t, (nn.Module, Tensor)):
            return t.to(device)
        return t

    return nested_map(move, ts)


def nested_map(func, ts,full=False):
    if isinstance(ts, torch.Size):
        # size is inheriting from tuple which is stupid
        return func(ts)
    elif isinstance(ts, (list, tuple, set)):
        return type(ts)(nested_map(func, t,full=full) for t in ts)
    elif isinstance(ts, dict):
        return {k: nested_map(func, v,full=full) for k, v in ts.items()}
    elif isinstance(ts, slice) and full:
        start = nested_map(func, ts.start,full=full)
        stop = nested_map(func, ts.stop,full=full)
        step = nested_map(func, ts.step,full=full)
        return slice(start, stop, step)
    return func(ts)


def flatten(ts):
    if isinstance(ts,torch.Size):
        # size is inheriting from tuple which is stupid
        yield ts
    elif isinstance(ts, (list, tuple, set)):
        yield from chain(*[flatten(t) for t in ts])
    elif isinstance(ts, dict):
        yield from chain(*[flatten(t) for k,t in sorted(ts.items(),key=lambda t:t[0])])
    else:
        yield ts


def unflatten(xs,structure):
    return _unflatten(xs,structure)[0]


def _unflatten(xs,structure):
    if isinstance(structure,torch.Size):
        #torch.Size is subclass of tuple which is stupid
        return xs[0],1

    if not isinstance(structure,(list,tuple,set,dict)):
        return xs[0],1
    
    if isinstance(structure,(list,tuple,set)):
        offset=0
        elements = []
        for s in structure:
            e,n = _unflatten(xs[offset:],s)
            elements.append(e)
            offset += n
        
        return type(structure)(elements),offset
    
    assert isinstance(structure,dict)
    offset = 0
    elements = dict()
    for k,v in sorted(structure.items(),key=lambda t: t[0]):
        e,n = _unflatten(xs[offset:],v)
        elements[k] = e
        offset += n
    
    return elements,offset


def state_dict(partition, *args,**kwargs):
    # we return the state dict of this part as it should be in the original model
    state = nn.Module.state_dict(partition,*args,**kwargs)
    lookup = partition.lookup
    result = dict()
    for k, v in state.items():
        if k in lookup:
            result[lookup[k]] = v
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            result[new_k] = v
    return result


def load_state_dict(partition, state):
    reverse_lookup = {v: k for k, v in partition.lookup.items()}
    device = partition.device
    keys = list(partition.state_dict(None).keys())
    new_state = dict()
    for k in keys:
        if k in reverse_lookup:
            new_state[reverse_lookup[k]] = state[k].to(device)
            continue
        idx = k.rfind(".")
        to_replace = k[:idx]
        if to_replace in reverse_lookup:
            key = reverse_lookup[to_replace] + k[idx:]
            new_state[key] = state[k].to(device)
    nn.Module.load_state_dict(partition, new_state, strict=True)


def named_buffers(partition, recurse=True):
    # we return the named buffers of this part as it should be in the original model
    params = nn.Module.named_buffers(partition, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield (lookup[k], v)
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield (new_k, v)


def named_parameters(partition, recurse=True):
    # we return the named parameters of this part as it should be in the original model
    params = nn.Module.named_parameters(partition, recurse=recurse)
    lookup = partition.lookup
    for k, v in params:
        if k in lookup:
            yield (lookup[k], v)
        else:
            assert '.' in k
            split_idx = k.find('.')
            new_k = lookup[k[:split_idx]] + k[split_idx:]
            yield (new_k, v)


def cpu(partition):
    partition.device = torch.device('cpu')
    return nn.Module.cpu(partition)


def cuda(partition, device=None):
    if device is None:
        device = torch.cuda.current_device()
    partition.device = torch.device(device)
    return nn.Module.cuda(partition, partition.device)


def to(partition, *args, **kwargs):
    device = None
    if 'device' in kwargs:
        device = kwargs['device']
    elif 'tensor' in kwargs:
        device = kwargs['tensor'].device
    if args:
        if isinstance(args[0], (torch.device, int, str)):
            device = args[0]
        if torch.is_tensor(args[0]):
            device = args[0].device
    if not (device is None):
        partition.device = torch.device(device)
    return nn.Module.to(partition, *args, **kwargs)

model_args = {'model_name_or_path': 't5-3b', 'max_seq_length': 128, 'answer_max_seq_length': 16, 'stateless_tied': True, 'lmhead': True, 'precompute_masks': True}
"""analysis summary
-I- Printing Report
warnings:
Partition0 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_1 is not contiguous!
Partition1 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_2 is not contiguous!
Partition2 output:T5ForConditionalGeneration/T5Stack[encoder]/tuple::__getitem___22_3 is not contiguous!
Partition3 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_4 is not contiguous!
Partition3 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_4 is not contiguous!
Partition4 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_5 is not contiguous!
Partition4 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_5 is not contiguous!
Partition5 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_6 is not contiguous!
Partition5 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_6 is not contiguous!
Partition6 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___130_7 is not contiguous!
Partition6 output:T5ForConditionalGeneration/T5Stack[decoder]/tuple::__getitem___132_7 is not contiguous!
Number of stages: 8
cutting edges are edges between partitions
number of cutting edges: 34

backward times include recomputation

Stage parameter count:
 {0: 385235968,
 1: 352335872,
 2: 352335872,
 3: 419451904,
 4: 335559680,
 5: 335559680,
 6: 335559680,
 7: 368459776,
 'total': 2884498432}

real times are based on real measurements of execution time (with communication) of generated partitions ms
forward {0: 13.49, 1: 12.5, 2: 12.64, 3: 13.83, 4: 12.07, 5: 11.8, 6: 11.9, 7: 11.99}
backward {0: 31.36, 1: 28.29, 2: 28.51, 3: 37.76, 4: 29.07, 5: 28.72, 6: 28.56, 7: 30.05}

Assuming bandwidth of 12 GBps between GPUs

communication volumes size of activations of each partition
0: input size:'0.00 MB', recieve_time:'0.00 ms', out:'2.69 MB', send time:'0.22 ms'
1: input size:'2.62 MB', recieve_time:'0.22 ms', out:'2.62 MB', send time:'0.22 ms'
2: input size:'2.62 MB', recieve_time:'0.22 ms', out:'2.62 MB', send time:'0.22 ms'
3: input size:'2.69 MB', recieve_time:'0.22 ms', out:'0.88 MB', send time:'0.07 ms'
4: input size:'0.89 MB', recieve_time:'0.07 ms', out:'0.88 MB', send time:'0.07 ms'
5: input size:'0.89 MB', recieve_time:'0.07 ms', out:'0.88 MB', send time:'0.07 ms'
6: input size:'0.89 MB', recieve_time:'0.07 ms', out:'0.88 MB', send time:'0.07 ms'
7: input size:'0.89 MB', recieve_time:'0.07 ms', out:'0.00 MB', send time:'0.00 ms'

Compuatation Communication ratio (comp/(comp+comm)):
forward {0: 0.98, 1: 0.98, 2: 0.98, 3: 0.99, 4: 0.99, 5: 0.99, 6: 0.99, 7: 1.0} 
backward {0: 1.0, 1: 0.99, 2: 0.99, 3: 0.99, 4: 1.0, 5: 1.0, 6: 1.0, 7: 1.0}

Analysis for T = fwd + bwd:
 {'expected_compute_utilization': {0: 0.87,
                                  1: 0.79,
                                  2: 0.79,
                                  3: 1.0,
                                  4: 0.8,
                                  5: 0.79,
                                  6: 0.79,
                                  7: 0.82},
 'pipeline_no_comm': {0: 44.63,
                      1: 40.35,
                      2: 40.71,
                      3: 51.29,
                      4: 41.0,
                      5: 40.38,
                      6: 40.31,
                      7: 41.97,
                      'worstcase': 51.29},
 'pipeline_vs_seq_no_comm': 5.12,
 'pipeline_with_non_parallel_comm': {0: 44.85,
                                     1: 40.79,
                                     2: 41.15,
                                     3: 51.58,
                                     4: 41.14,
                                     5: 40.53,
                                     6: 40.46,
                                     7: 42.04,
                                     'worstcase': 51.58},
 'seq_no_comm_no_recomp': {0: 33.75,
                           1: 31.15,
                           2: 31.51,
                           3: 39.44,
                           4: 31.35,
                           5: 31.26,
                           6: 31.6,
                           7: 32.59}}

Analysis for T = (1-R)fwd + R*bwd:

Pipeline Slowdown: (compared to sequential executation with no communication, and same recompute policy)
forward 1.114
backward 1.251

Expected utilization by partition
forward {0: 0.96, 1: 0.88, 2: 0.89, 3: 0.99, 4: 0.86, 5: 0.84, 6: 0.85, 7: 0.87}
backward {0: 0.83, 1: 0.74, 2: 0.75, 3: 0.99, 4: 0.77, 5: 0.76, 6: 0.76, 7: 0.8}

worstcase: bwd: 37.758 fwd: 13.826
expected_speedup_compared_to_seq_no_recomp_no_comm: 5.091
Expected speedup for 8 partitions is: 6.586
max cuda memory used 3.37GB
"""